### PR TITLE
Clean dependencies

### PR DESCRIPTION
**Pull request by aquacash5**
Removes extra dependencies from packages and moves the example to a sub-project.

### CODE REVIEW

**Comment by jschomay** [comment]
Good call @aquacash5.  Thanks for the PR!

I'd like to tie up a few loose ends, then I'll merge and make a new release:

1. Update the link to the example source in `README.md`.
1. `elm bump` for me.  I think it will be a patch level diff.
1. Question - do you want to move `index.html` into `exmple/`?  That might be a little clearer, I'll just need to change the github pages set up.  If it doesn't bother you in root then leave it.  Also, you could regenerate it, but I don't think that is necessary.

After that I can merge/tag/release.

Thanks again and glad you are using elm-paginate!

**Comment by aquacash5** [comment]
I don't know if you saw my new commits, but went ahead and did what you asked.

**Comment by jschomay** [comment]
Awesome, thank you!  I can't get to it right now, but I will soon.

**Comment by jschomay** [comment]
Thanks again @aquacash5 !  https://package.elm-lang.org/packages/jschomay/elm-paginate/3.1.2/ is live :)

**Pull request merged**
